name: Test Workflow
on: [push]
env:
  CI: true
jobs:
  analyze_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest state
        uses: actions/checkout@v2
      - name: Gas
        run: |
         yarn install
         npx hardhat compile 
         npx hardhat test
      - name: Coverage 
        run: |
          npx hardhat coverage && npx istanbul check-coverage --statements 88
      - name: Solhint
        run: |
          npx solhint 'contracts/**/*.sol' -w 0
