name: Test Workflow
on: [push]
env:
  CI: true
jobs:
  analyze_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest state
        uses: actions/checkout@v2
      - name: Gas
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 15
          command: |
           yarn install
           yarn compile 
           yarn test
      - name: Coverage
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 15
          command: |
            npx hardhat coverage && npx istanbul check-coverage --statements 88
      - name: Solhint
        run: npx solhint 'contracts/**/*.sol' -w 0
