name: Test Workflow
on: [push]
env:
  CI: true
jobs:
  analyze_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest state
        uses: actions/checkout@v2
      - name: Gas
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          command: |
           yarn install
           npx hardhat compile 
           npx hardhat test
      - name: Coverage 
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          command: |
            npx hardhat coverage && npx istanbul check-coverage --statements 88
      - name: Solhint
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          command: |
            npx solhint 'contracts/**/*.sol' -w 0
